# Generated by Django 4.2.28 on 2026-02-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=100)),
                ('report_date', models.DateField()),
                ('document', models.FileField(upload_to='reports/')),
            ],
        ),
    ]
