# Generated by Django 4.2.28 on 2026-02-04 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditreport',
            old_name='reference',
            new_name='credit_risk',
        ),
        migrations.RenameField(
            model_name='creditreport',
            old_name='report_date',
            new_name='expiry_date',
        ),
        migrations.AddField(
            model_name='creditreport',
            name='beneficiary_address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditreport',
            name='beneficiary_name',
            field=models.CharField(default='bene', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditreport',
            name='entry_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditreport',
            name='entry_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditreport',
            name='lc_number',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditreport',
            name='line_of_business',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditreport',
            name='related_party',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditreport',
            name='vendor_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
