# Generated by Django 4.2.28 on 2026-02-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_rename_reference_creditreport_credit_risk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditreport',
            name='beficiary_country',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
