# Generated by Django 4.2.28 on 2026-02-05 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_creditreport_beficiary_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditreport',
            old_name='beficiary_country',
            new_name='beneficiary_country',
        ),
    ]
