# Generated by Django 4.2.28 on 2026-02-05 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0004_rename_beficiary_country_creditreport_beneficiary_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lc_number', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=255)),
                ('beneficiary_name', models.CharField(max_length=255)),
                ('beneficiary_address', models.TextField()),
                ('beneficiary_country', models.CharField(max_length=255)),
                ('related_party', models.CharField(max_length=100)),
                ('vendor_name', models.CharField(max_length=255)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('request_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
